# Site settings
name: Less Or More
email: todguo86@utexas.edu
author: Sifan Guo
url:
resume_site: https://sifanguo.github.io/resume.html
github: https://github.com/SifanGuo
baseurl: ""
description: Actually, less is more!
meta_description: Data Science; Half Blockchain developer;
motto: Time is limited. That's why I want Less pain, more gain. :-)
banner: 知易行难，总得学以致用。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: SifanGuo

# Build settings
markdown: kramdown

baidu_analysis: 8289a5f335ca2aa59ed3485235925c2d
